### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by cropinghigh** [deathmarine/Luyten#123]
I got this error when I tried to decompile a class that is not designed to decompile (Minecraft's password protection class). In this case, the final application is working normally, without errors. How can I fix this? (Do not think wrong, I do not want to hack that server, I want to test it for security vulnerability).

**Comment by deathmarine** [comment]
Considering this software exists there are some that will attempt to defeat it. This happens regularly. However you may have to do some investigating to determine what the decompiled file is doing. Layer and layer of obfuscation and encryption will not decompile easily if at all.
