### ISSUE TITLE
java.lang.IllegalStateException: Wrong magic number: 1982898694

### ISSUE THREAD

**Issue by maaadmin** [deathmarine/Luyten#168]
Hello, I was decompiling a jar file and this error has occurred, can anyone explain it?
java.lang.IllegalStateException: Wrong magic number: 1982898694
	at com.strobel.assembler.metadata.ClassFileReader.readClass(ClassFileReader.java:337)
	at com.strobel.assembler.metadata.MetadataSystem.resolveType(MetadataSystem.java:124)
	at com.strobel.assembler.metadata.MetadataSystem.lookupTypeCore(MetadataSystem.java:81)
	at com.strobel.assembler.metadata.MetadataResolver.lookupType(MetadataResolver.java:46)
	at us.deathmarine.luyten.Model.openEntryByTreePath(Model.java:338)
	at us.deathmarine.luyten.Model$TreeListener$1.run(Model.java:266)

**Comment by greenozon** [comment]
@maaadmin 
1) read what is magic number inside java class file
https://en.wikipedia.org/wiki/Java_class_file

2) it'd be much easier for the author of the tool to understand what's going on in case you attach your jar!

my assumption is that your jar/.class file(s) is (are) encrypted.

Luyten works with plain java classes only.

**Comment by maaadmin** [comment]
> @maaadmin
> 
> 1. read what is magic number inside java class file
>    https://en.wikipedia.org/wiki/Java_class_file
> 2. it'd be much easier for the author of the tool to understand what's going on in case you attach your jar!
> 
> my assumption is that your jar/.class file(s) is (are) encrypted.
> 
> Luyten works with plain java classes only.

thanks for the information, so if it was encrypted there is no solution to decrypt it?

**Comment by greenozon** [comment]
if your app runs OK -> there is a way, for sure
you have to analyze yourself (most probably that's another .jar, or it maybe native code...

**Comment by maaadmin** [comment]
> if your app runs OK -> there is a way, for sure
> you have to analyze yourself (most probably that's another .jar, or it maybe native code...

thank you again..

**Comment by deathmarine** [comment]
I would say the jar is either corrupt, or the class could be encrypted, the software could be decrypting classes and loading them later as a sort of obfuscation. Either way I can only reproduce this intentionally, by renaming a binary file to class and putting it in a jar.
You may have to do a little more investigation, look for a class extending Classloader and pulling resources from the jar. I once wrote a wrapper that would decrypt and load each class and after phoning home and authenticating using a public and private key. Either way there is something else going on here.
