### ISSUE TITLE
Find in .jar?

### ISSUE THREAD

**Issue by joshsleeper** [deathmarine/Luyten#22]
Any chance we can get a find feature implemented that allows us to do a text search of all files, or at least all files in a folder/subfolder we define? Unless I'm missing an easier way, it's a pain to search through a bunch of different class files just to find where some method is called.

**Comment by deathmarine** [comment]
2e316c56cbc5b345854a662ac4b53b4a8387cd90
Ctrl-Click Navigation makes following code path a bit easier.

**Comment by joshery420** [comment]
Great, thanks so much @deathmarine! :+1:

**Comment by z3ntu** [comment]
Closed?

**Comment by deathmarine** [comment]
I think this is resolved.
