### ISSUE TITLE
Won't launch, com/apple/eawt/ApplicationListener

### ISSUE THREAD

**Issue by caesartcs** [deathmarine/Luyten#264]
Installed luyten from brew cask and it will not launch.

Running `/Applications/Luyten.app/Contents/MacOS/universalJavaApplicationStub.sh Desktop/sample.jar`
I get the following:
```
Error: Unable to initialize main class us.deathmarine.luyten.LuytenOsx
Caused by: java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener
```

MacOS 10.15.7
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

Anyone familiar with this?

**Comment by caesartcs** [comment]
Looking into it further, it seems that the file **LuytenOsx.java** is for allowing the drag-and-drop for functionality in OSX. This can very well run on Catalina I believe if we removed instances of `import com.apple.eawt.*`

However I can't even install from source with maven as is without getting a `incompatible types` error. Someone who knows java might be able to solve this

**Comment by tyh999908** [comment]
I have the same problem

**Comment by caesartcs** [comment]
Closing. 

The reason it doesn't work is because **com/apple/eawt** is no longer available in Catalina. But I removed the imports from **com/apple/eawt** and built it from source.

Originally I had it installed from **brew** and that copy of Luyten didnt work but installing it with **maven using java 8 works**.

A quick how-to for others:
```
brew install maven # this will also install openjdk as a dependency (java version 15)
brew install openjdk@8
sudo ln -sfn /usr/local/opt/openjdk@8/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-8.jdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home/

cd Luyten
java -version # should be openjdk version "1.8.0_275", if its version 15, remove the openjdk package even though maven relies on it as a dependency
mvn -version # should be Java version: 1.8.0_275
mvn clean install
```
Newly compiled **Luyten.app** should appear at `Luyten/target/Luyten.app`

Note: I had to uninstall **openjdk** (which is version 15, _not openjdk@8_) forcefully using brew because it kept being set as default jdk for maven. And I had to remove the `openjdk.jdk` link from `Library/Java/JavaVirtualMachines/`. 
Hope this helps somewhat.
