### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#27]
1) Please add the support for [Enter] key while navigating the left tree like panel with classes (= double click by mouse)
2) While cursor is in Code panel (java source) please add support for CTRL + F4 key combination (to close the current tab

Thanks

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/blob/master/src/us/deathmarine/luyten/MainMenuBar.java#L121-L232

I have accelerators for most keyboard commands Close is Ctrl + W closes the open doc as opposed to the reverse which in most cases Ctrl + F4 is normally close and Ctrl + W is close tab. I will most likely take that route.
Ref: http://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

As for [Enter] to open a selected tree item, I concur.

**Comment by greenozon** [comment]
Hi
Thanks, agree with 1st part, just need a fast combination to close 10-th, 100th of opened tabs...

on 2) The idea was to have a fast mean to navigation 100-th of java files without clicking the mouse button, so using [Enter] on selected tree item come as the 1st idea to my mind
If there are other combinations- that will be fine as well, the final goal is user convenience of the Luyten tool usage by keyboard only!

3) Menu item File - Recent files is always disabled (grayed out) - is it a feature to be implemented?
usually thats also a level of user-friendliness

4) Another idea, maybe worth tracking by a separate  issue - Advance the classes navigation, yeah. I'll open up a new one right now...

**Comment by deathmarine** [comment]
#62 Closes this.
