### ISSUE TITLE
Fresh build of Luyten using latest sources

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#289]
I've built a latest binary of Luyten using latest sources of Procyon (post 0.5.36)
It's available here:  https://www.sendspace.com/file/ql7tup

Notes:
I have to remove some patches inside Procyon for proper parsing of BootstrapMethods attribute 
This attribute might have modern stuff from Java 9+ like

StringConcatFactory::makeConcat
StringConcatFactory.makeConcatWithConstants

There is no support currently for these kind of methods inside Procyon.
Looks like development of it is on hold....

The current patch will allow to browse source code, but instead of string concatenations you'll see something like

```
    public String toString() {
        return invokedynamic(makeConcatWithConstants:(I)Ljava/lang/String;, this.str1);
    }
```

**Comment by greenozon** [comment]
Potentially this fixes assertions/error boxes for the following issues:

https://github.com/deathmarine/Luyten/issues?q=is%3Aissue+is%3Aopen+invalidBootstrapMethodEntry

#279
#277
#260
#246
#231
#224
#218
#217
#216
#211
#209
#207
#201
#187
#185
#180
#178
#164
#158
#144
#133
#102

**Comment by ThexXTURBOXx** [comment]
I also provided a build with Java 9+ support in my fork. See #292 for more details.

**Comment by greenozon** [comment]
Looks like we have lightning breaking news!
#296

**Comment by ThexXTURBOXx** [comment]
Had already been incorporated in my fork for quite some time :)

**Comment by greenozon** [comment]
I"ve built fresh build of Luyten and put here https://www.sendspace.com/file/lyyng5
it is based on procyon engine 0.6.0 which resolves majority of Java 8+ issues

**Comment by ThexXTURBOXx** [comment]
@greenozon Why? See #292 for a download with many more fixes apart from just a Procyon update :)

**Comment by greenozon** [comment]
I dont understand your update, please walk your path, why putting obstacles to others?

**Comment by ThexXTURBOXx** [comment]
@greenozon I am not putting obstacles in anyone's way. In fact, I am removing most of the obstacles by fixing many bugs in Luyten.
My update is available here: https://github.com/ThexXTURBOXx/Luyten/releases/tag/v0.8.1
And it also features the Procyon 0.6.0 update. But also fixes many other bugs as well.

Addendum: Also, I would not trust a random sendspace.com download. Especially not if there is an open source alternative that does the same thing with many more other fixes as well...

**Comment by greenozon** [comment]
Everybody has a right to educate theirselves and improve the skills
you have your own path - good luck
others are doing their path, 
**so why bother?**

you do not trust - thats your problem
