### ISSUE TITLE
Version in about dialog

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#29]
Idea: add versions of the Luyten tool itself and version of used Procyon engine in the About dialog.
Consider adding the build time of the tool as well (not sure if that's possible at all in java.... I know it is being supported by for example C, C++ compiler in compile time by special macros)

**Comment by deathmarine** [comment]
With maven I can however depending with the repository data being outdated, I've been having to manually load the procyon library.

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/commit/492b9820c401e4c8b047fe2bc3563bb5833bba99#diff-d65560be173f45c02938cd91cc4a4a39R466

Portion of this has been added
