### ISSUE TITLE
the version "luyten-0.5.4.exe" does not support openjdk .

### ISSUE THREAD

**Issue by hellozrh** [deathmarine/Luyten#314]
the version "luyten-0.5.4.exe" does not support openjdk

![image](https://user-images.githubusercontent.com/12250931/236597848-da88cc20-c172-4fb1-88d5-ebc34f7bb88c.png)

my java home info :

```shell
C:\WINDOWS\System32>java -version
openjdk version "1.8.0_362-362"
OpenJDK Runtime Environment (build 1.8.0_362-362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

**Comment by hellozrh** [comment]
os enviroment:
![image](https://user-images.githubusercontent.com/12250931/236610827-7845fb71-e8da-42c1-abaf-79f2fbfe57b0.png)

**Comment by ghost** [comment]
As a workaround, you can open the .JAR version from a Terminal like this: `javaw -jar luyten-0.5.4.jar`
