### ISSUE TITLE
Can't render the java class - String index out of bounds

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#33]
Drag-dropping 1 class file onto ver 4.4 shows this:

http://prntscr.com/73oujf
no content of decompiled class
when clicking the class file in left most tree - same error

**Comment by deathmarine** [comment]
I've tried several different class files alone, the only way I've seen to reproduce anything close to this is with a blank file. Do you have anymore information on how you produced this exception?

**Comment by greenozon** [comment]
do you have some PM so I"ll send you the sample?
thanks for undertanding

**Comment by greenozon** [comment]
Attached another sample wiht String index out of bounds error
https://www.sendspace.com/file/2q7twg

**Comment by deathmarine** [comment]
![Unable to Reproduce](http://i.imgur.com/4c6wD9P.png?1)

What operating system is the happening in?

**Comment by greenozon** [comment]
Win7 x64 eng sp1

**Comment by greenozon** [comment]
maybe you are using nightly build and not the latest release from download page?

**Comment by balidani** [comment]
I have the same issue on Ubuntu. Stack trace: https://gist.github.com/balidani/a8e51dd76463591c9bd1

**Comment by greenozon** [comment]
Could we make progress here please?
the stack from balidani is very direct...

**Comment by deathmarine** [comment]
@greenozon Could you send that sample again.

**Comment by greenozon** [comment]
sorry can't find that error file for the moment.......
but is the info form balidani enough to track error down?/

**Comment by deathmarine** [comment]
This looks like a procyon error, 
https://bitbucket.org/mstrobel/procyon/issues/230/decompiler-errors-during-decompilation-of
however I can't reproduce with file uploaded.

**Comment by greenozon** [comment]
Agree,
must be old procyon error
issue  gone on latest luyten 045 backed by procyon 032, thus closing
