### ISSUE TITLE
Objects ending with 2 and 3 being merged and treated as if they were the same

### ISSUE THREAD

**Issue by mrCookieSlime** [deathmarine/Luyten#34]
If you define two Objects ending with 2 and 3 they are being merged into the first Variable defined.

Code:

int min2 = main.cfg.getInt("enchantments.min");
int max2 = main.cfg.getInt("enchantments.max");
int min3 = main.cfg.getInt("potions.min");
int max3 = main.cfg.getInt("potions.max");

Luyten Output:

int min2 = main.cfg.getInt("enchantments.min");
int max2 = main.cfg.getInt("enchantments.max");
min2 = main.cfg.getInt("potions.min");
max2 = main.cfg.getInt("potions.max");

Third Party Decompiler:

int min2 = main.cfg.getInt("enchantments.min");
int max2 = main.cfg.getInt("enchantments.max");
int min3 = main.cfg.getInt("potions.min");
int max3 = main.cfg.getInt("potions.max");

It was compiled correctly as the other Decompiler I used has proven.
However Luyten somehow merged both Variables.
And it is not only me who this is happening to, Myrathi was the first one to encounter this Bug.

Version of Luyten used: Luyten 0.4.4 (latest)
File this was encountered on: http://dev.bukkit.org/media/files/878/538/MagicLoot_v2.1.0.jar

**Comment by Myrathi** [comment]
Acknowledging ticket. Testing decompile via JD-GUI shows correct code.

**Comment by deathmarine** [comment]
http://imgur.com/Kkj054T

**Comment by mrCookieSlime** [comment]
Sorry for the delay. Here is a screenshot proving that this was indeed encountered when viewing this file:
![Screenshot](http://i.gyazo.com/9d68a3c6abe22706e15096829bbe1a26.png)
Perhaps you were simply using an outdated Version of JD-GUI?
Fact is that I can confirm that the Code shown by my JD-GUI Version matches my Source Code I used when compiling the Plugin.

**Comment by deathmarine** [comment]
I believe this is an issue with Procyon, I've reported the issue and has been resolved.
https://bitbucket.org/mstrobel/procyon/issues/262/multiple-variable-declarations-fails
This will be resolved in the next build of Luyten

**Comment by mrCookieSlime** [comment]
Ah okay, thank you very much I will let the rest of the Bukkit Team know this.
Thanks for your assistance.

**Comment by mrCookieSlime** [comment]
Reopened until Fix is published and tested.
(Myrathi was yelling at me :P )

**Comment by deathmarine** [comment]
Newest builds seemed resolved.
![](http://i.snag.gy/0MEqf.jpg)
