### ISSUE TITLE
Find All requires focus, Find dialog hides when it loses focus

### ISSUE THREAD

**Issue by zhengbing1206** [deathmarine/Luyten#40]
![qq 20150915155253](https://cloud.githubusercontent.com/assets/6149628/9870824/d7af99bc-5bc1-11e5-867e-29f95686a88c.png)
OS：windows server 2012 R2

**Comment by deathmarine** [comment]
Original Title:
在使用Find或Find ALL查找代码内容时，程序不能在后台中运行，在和其他任务切换时程序会被中断

Translation via Google: 
When using the Find or Find ALL lookup code content , the program can not run in the background when switching program and other tasks will be interrupted

Find dialog hides when it loses focus and Find All requires focus.

To be honest I'm not a fan of the "find" and "find all" dialogs. The find all dialog, decompiles a file, scans the file, and logs the file if the instance of what your searching for is found. This was never a finished product but it was functional. This can be implemented but the time to work out issues between threads would be difficult.

**Comment by LPK-Matt** [comment]
Would using a library such as ASM to search for things be something you'd be willing to do? I use it in a project of mine and searching for things (string literals, method/field references) is nearly instant.

**Comment by deathmarine** [comment]
Interesting idea, however with ASM don't you have to load the files. I mean I could write a classloader that could unload files but I'm not sure it would be as efficient. If I get time I may try to rework it.

**Comment by LPK-Matt** [comment]
If by loaded you mean keeping the file constantly open [it appears so](http://i.imgur.com/w1sOIwQ.png). With my project I just read the jar to a map of class names to class nodes and close off the inputstream to the jar. So no you don't have to worry about unloading classes. It's completely static-analysis.

**Comment by deathmarine** [comment]
The file is in use because of the way Luyten navigates the zip, but none of the files are loaded to the JVM. I'm not sure if I want to load an entire Jar just to navigate through it, not without unloading.
