### ISSUE TITLE
[Request] change the file chooser to OS file chooser

### ISSUE THREAD

**Issue by pangeacake** [deathmarine/Luyten#41]
The swing file chooser is much harder to use.

**Comment by virustotalop** [comment]
What does your file chooser look like? I'm not getting a swing interface.
![luyteninterface](https://cloud.githubusercontent.com/assets/11567285/10472314/c317daa0-71d3-11e5-9e03-df721f39c9c6.png)

**Comment by pangeacake** [comment]
Er, that's what I meant. Personally I think it'd be a lot easier to use if it just used Windows's file chooser.

**Comment by virustotalop** [comment]
Are you using a release build or compiling from source? I haven't checked the release build but compiling from source gets you the result above.

**Comment by pangeacake** [comment]
That is what I see but I think this would be better:


![](http://i.stack.imgur.com/lNOWC.png)

**Comment by deathmarine** [comment]
That screenshot although java, is a home made window from eclipse.
https://github.com/eclipse/eclipse.platform.ui/blob/deda98de807d32a42163a72792b2b8ca1d59a193/bundles/org.eclipse.ui.navigator.resources/src/org/eclipse/ui/internal/navigator/resources/actions/OpenActionProvider.java
Implementing this would not be a very easy task, but it is not an os file chooser, this can be called up with a native api however adding more dependencies will increase the size of Luyten's jar. Other than aesthetics, I don't really think this is necessary going forward.
