### ISSUE TITLE
Save All issue...

### ISSUE THREAD

**Issue by pavankumarpisipati** [deathmarine/Luyten#42]
When I merged all the three(Luyten GUI, RSyntaxArea and Procyon Decompiler), I found an issue when trying to save the sources in the form of zip. Please fix the issue for Save All...menu item.

Thanks

**Comment by deathmarine** [comment]
Could you describe the issue in greater detail, I'm unsure what you issue for Save All... I attempted to save-all / decompile itself and I'm successful, If you can elaborate on your issue I'd be happy to help.

**Comment by deathmarine** [comment]
Duplicates #11
