### ISSUE TITLE
Latest sources not compilable

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#43]
Error:

-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
us/deathmarine/luyten/ConfigSaver.java:[61,39] cannot find symbol
  symbol:   method getFormattingOptions()
  location: variable decompilerSettings of type com.strobel.decompiler.DecompilerSettings
us/deathmarine/luyten/ConfigSaver.java:[62,43] cannot find symbol
  symbol:   method setFormattingOptions(com.strobel.decompiler.languages.java.JavaFormattingOptions)
  location: variable decompilerSettings of type com.strobel.decompiler.DecompilerSettings
2 errors 
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.617s
Finished at: Sat Nov 21 11:08:02 EET 2015
Final Memory: 10M/28M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project luyten: Compilation failure: Compilation failure:
us/deathmarine/luyten/ConfigSaver.java:[61,39] cannot find symbol
symbol:   method getFormattingOptions()
location: variable decompilerSettings of type com.strobel.decompiler.DecompilerSettings
us/deathmarine/luyten/ConfigSaver.java:[62,43] cannot find symbol
symbol:   method setFormattingOptions(com.strobel.decompiler.languages.java.JavaFormattingOptions)
location: variable decompilerSettings of type com.strobel.decompiler.DecompilerSettings
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by greenozon** [comment]
Building from NB 8.0.2

**Comment by matthewwc** [comment]
Getting a similar error as @greenozon, here's a paste of the mvn clean package logs: 
https://share.riseup.net/#Y2e0Xu_F-K10OcyiUa0pog

**Comment by greenozon** [comment]
Thank you for the fix & update!
consider creating a new release + version used in About dlg

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/commit/20eafd2a5278850b3545d031b30ee67292daadb3
