### ISSUE TITLE
Wrong line numbers

### ISSUE THREAD

**Issue by Slind14** [deathmarine/Luyten#46]
When using Luyten I always have an issue on finding the right line in relation to a stack trace. They are always way off. Is there a setting I might not have found yet? I haven't experienced this with jdgui, yet.

**Comment by deathmarine** [comment]
Luyten displays the output from Procyon with no relation to line number, however it seems this has been noted and is experimental within procyon.
https://bitbucket.org/mstrobel/procyon/issues/163/line-numbers-dont-match-class-files
Implementing stretch lines would require a bit or a larger addition as I would have to rewrite the classes to modify the file output from Procyon's LineFormatter classes 
https://bitbucket.org/mstrobel/procyon/src/fa7db1e6bf42bfee84f6f4c58fd9668ee290802e/Procyon.Decompiler/src/main/java/com/strobel/decompiler/DecompilerDriver.java?at=default&fileviewer=file-view-default#DecompilerDriver.java-345

However in the mean time I've implemented the options to show the correct line numbers in comments.

**Comment by Slind14** [comment]
alright, thanks :)
Do I have to tick a config option for them to show in the comments/enable the comments?

**Comment by deathmarine** [comment]
If you build the newest version of Luyten,
![](http://i.snag.gy/maVKm.jpg)

**Comment by Slind14** [comment]
:+1:

**Comment by 75ACOL** [comment]
Can you align line numbers?

**Comment by 75ACOL** [comment]
Can you align line numbers? Jd-gui has this feature, which is great for code debugging
