### ISSUE TITLE
Read, Please...

### ISSUE THREAD

**Issue by jordanwilliams1** [deathmarine/Luyten#47]
Okay,

So my server has been running one of your plugins for nearly 2 years now, The plugin is called "DiabloDrops" 

This is a really good plugin, It works 100% fine but we have 1 problem that no one can fix. Whats the bug? When you socket a item in a furance there is a chance it would break, Can you please fix this for me? I Will even pay you if you can fix it for me. My skype is: thepotatoarmyhd

Sorry for posting here but i don't think i can private message you.

**Comment by deathmarine** [comment]
This is definitely not the place for this.
