### ISSUE TITLE
Update version in pom.xml

### ISSUE THREAD

**Issue by toonetown** [deathmarine/Luyten#49]
The latest released version is 0.4.6 - but the pom.xml still shows 0.4.5.

Not sure if the versions are controlled somewhere else...I thought perhaps this was just an oversight.

I can create a pull request for this if you like - but as it is super trivial, I thought I'd just report it as an issue (and you can either fix, ignore, or close this issue as you need).

**Comment by deathmarine** [comment]
Wow thanks, must of slipped by me. I'll make the change.
