### ISSUE TITLE
Cancel "Find All" while searching in one .class file

### ISSUE THREAD

**Issue by z3ntu** [deathmarine/Luyten#52]
When the "Find All" dialog searches in all files and you press cancel, it will only cancel at the next .class file to decompile, but it should cancel immediately.

**Comment by deathmarine** [comment]
We can store and interrupt the thread, but I don't understand why this would be an issue unless your class files are massive or your working on a 486...

**Comment by z3ntu** [comment]
Yes, it was a massive file.

**Comment by deathmarine** [comment]
To be honest I never actually used this functionality, I was under the assumption that you could "double click" a link and it would open. I'm going to do some work on this.

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/commit/7b355607eb3360db053d05db4f3d500d79032b17
https://github.com/deathmarine/Luyten/commit/f19b098c98cd9f6dfecdbdccfbff494658a9fde6
