### ISSUE TITLE
code font size is too small to see.

### ISSUE THREAD

**Issue by everhad** [deathmarine/Luyten#53]
On PC, in the high resolution screen, code size is too small to see.

**Comment by everhad** [comment]
我增加了代码字体大小设置功能，提交了pull request.

**Comment by deathmarine** [comment]
I've reviewed your suggestion, and have decided to include a Ctrl+Wheel type zoom for enlarging and shrinking text as well as a Font Chooser to temporarily edit the viewable theme.

**Comment by deathmarine** [comment]
![Imgur](http://i.imgur.com/kfQgLLp.png?2)
![Imgur](http://i.imgur.com/kimjPny.png?2)
![Imgur](http://i.imgur.com/1yc52vm.png?3)
![Imgur](http://i.imgur.com/3OnD9tT.png?1)

**Comment by everhad** [comment]
That is good!

**Comment by deathmarine** [comment]
Thanks for the request. I'll close this issue.
