### ISSUE TITLE
"Save All" and "Find All" stuck at 50%

### ISSUE THREAD

**Issue by EndeR583** [deathmarine/Luyten#55]
This happens every time when I try to export or find words in a bigger (20 MB) jar file.

**Comment by EndeR583** [comment]
I'm sorry I waited an hour and it completed.

**Comment by deathmarine** [comment]
If anything I've personally had an obfuscated 10 Mb jar take a couple mins but not an hour. I'm going to reclose this as I don't believe there is an issue. I think under normal circumstances, with a fairly common machine, in any environment, anyone can get the same results.
