### ISSUE TITLE
Text on tabs cancels mouse events

### ISSUE THREAD

**Issue by Col-E** [deathmarine/Luyten#58]
video:  https://a.pomf.cat/xuemuq.mp4

As you roll over the sides of the tab it shows that it's being hovered over. But when you roll over the filename label it cancels the hover and makes it un-clickable.

This only occurs on the most recent release (0.48)

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/commit/5e41ff7957255ab9595555c061446e494b942759

Looks like this listener is the issue. Thanks for the report.
