### ISSUE TITLE
Search improvement - Hot Key Exploration

### ISSUE THREAD

**Issue by greenozon** [deathmarine/Luyten#78]
Hi
I've an idea - 
could you add a shortcuts for searching through the current decompiled code please?
use case:
Ctrl+F  - type text - start searching
then press F3 to continue searching next value and Shift +F3 to search backwards?

would be very handy I guess
thx!

**Comment by deathmarine** [comment]
???
![Example](https://i.snag.gy/pb01KE.jpg)

Opens

![Example](https://i.snag.gy/IFSxKi.jpg)

**Comment by greenozon** [comment]
OK, more details on idea

existing CTRL+F = OK
proposal is to add 2 more key combinations: F3 + SHIFT-F3 (when the find dialog will be closed)
these 3 keys should do the searching in direct or reverse direction

This is common practice and most SW having it... 
just a plus to the user experience, what do you think?

**Comment by deathmarine** [comment]
Hmm so kind of like Registry Explorer... Actually that would be pretty cool.

**Comment by greenozon** [comment]
Exactly!  most SW uses these search shortcuts and experienced users will say you a big thanks, no doubt! (including me 10 time :)

**Comment by deathmarine** [comment]
It'll be in the next build.
