### ISSUE TITLE
Please improve usability of UI with better searches and keyboard controls

### ISSUE THREAD

**Issue by oshvarts** [deathmarine/Luyten#79]
Please make the UI of this (already very nice and helpful) tool even better by adding a few more more search options and :

1) Allow class-level search, by class name ("String"), full package/ class name ("java.lang.String") or package abbreviation ("j.l.String")

2) When UI first loads a file, please show a floating search bar at top of main screen; it would allow searches right away, kind of like the search bar at the top of github does.

3) If I do control-F and the tool does not find anything, please show "no matches found" and stay in place instead of jumping to the top of the screen.

4) By default, do not wrap searches.  As is, I always have to keep an eye on the scrollbar to see if search just jumped to the top of the file (meaning there are no more results).  It's OK to have a checkbox option for it, but please don't do it by default.

5) Allow global full search (yes, even if it might be quite slow), covering full text of all classes, property files, mf files, etc.

6) After control-clicking and jumping to a class/method reference, allow "escape" key to close that window and return to the original location.

7) Close current window / class view using Control-F4.

Thank you!

**Comment by greenozon** [comment]
Good list!
my 5 cents if you don't mind:
#3 - extra dlg box might bother (you have to close it either my mouse or by ESC - extra moves...)
Should definitely stay still on the same place! +you might beep/buzz as a alarm that nothing found.
#4 - there was an idea to do F3/ShiftF3 (for reverse search)
#6 - is it IDA like? :)
#7 - I vote for it, its also a common short cut to close child window/tab  (btw, current tab closer = CTRL+W, this is less common but also used in some SW)

BTW, a shortcut CTRL+G  usually means GoTo Line in current window...
current one might be as a CTRL+SHIFT+F (mega find)

cheers

**Comment by oshvarts** [comment]
Thanks, @greenozon.  

Re 3, extra dialog might not be too much of a bother if closeable with "esc", since keys are on the keyboard already for the find operation, but it's ok not have it as long as there's visual indication nothing is found and I am not taken randomly to the top of the file. 

Re 4, not exactly the same, F3 just does a find next but if it still wraps search, no good.

Re 6, precisely, and it's used for approximately the same activities :)

Re 7, I did not realize Ctrl-w did the same, I am so very used to Ctrl-f4 in browsers and eclipse.  Can be lower priority if desired.

**Comment by deathmarine** [comment]
1.. You may need to elaborate on this. Are you searching for a class name?
2. There is a bit of structure to searches, Find (within a decompiled class) and Find All (which scans the entire jar, zip, ect...). Considering this is an application, I do not intend to add a search bar to the ui.
3. I can add this to the status bar in the bottom left of the main window.
4. Same as 4, I can add a checkbox to wrap
5. FindAll?
6. Conflicts with Operation -> Exit by Esc
7. Ctrl-F4 is fine, I can add it to the existing Ctrl-W, middle click, ect....

**Comment by oshvarts** [comment]
1. Yes, searching for a classname, or a subset of it.  For example, in Luyten itself, I might want to search for "FindBox", or "u.d.l.FindBox", or a subset like "FindB" and have it found quickly.  In a jar with hundreds of classes, scanning the tree on the left is sometimes quite tedious.
2. Why couldn't you add a search bar to an application?  A floating bar would be helpful to get started quickly.  It can disappear once a file is open, if you'd like.
3. That's ok, just make a "sound" like @greenozon said and stay where it was, do not jump to the top of the file.
5. FindAll works fine for finding things in classes, but it does not search properties files, .mf, xml, xsd, js files, etc. 
6. OK, maybe alt-left-arrow like eclipse does?

Thanks for consideration!!  :)

**Comment by deathmarine** [comment]
1. https://github.com/deathmarine/Luyten/commit/2ffb006d265d2e0e968b4dd20e1870a1eba2e17c Should fix that in the Findall Dialog
2. ...
3. https://github.com/deathmarine/Luyten/commit/befd23f431f03709df9bafef23b7aad2adcc76f2
4. https://github.com/deathmarine/Luyten/commit/befd23f431f03709df9bafef23b7aad2adcc76f2
5. https://github.com/deathmarine/Luyten/commit/56eb4b894540384799ae8fe903b404b3e2e8a18d Fixed Findall
6. Ctrl-F4 / Ctrl-W does the same thing, and esc is used to exit
7. https://github.com/deathmarine/Luyten/commit/7e6be078e7e1e5e089951aa6ebe2d6c7305713b1 Adds Ctrl-F4

Side note Ctrl-W will close the file if no tabs are open.

**Comment by deathmarine** [comment]
https://github.com/deathmarine/Luyten/releases/tag/v0.5.3

**Comment by oshvarts** [comment]
Thanks!!
