### ISSUE TITLE
Does not work with this file, fails on static declarations

### ISSUE THREAD

**Issue by CaledoniaProject** [deathmarine/Luyten#81]
I've uploaded it here

https://ufile.io/j5rma

Screenshot

![screen 2017-05-21 at 09 51 13](https://cloud.githubusercontent.com/assets/1357701/26280537/190e15aa-3e0b-11e7-8066-2a0705f0f7e4.jpg)

Can you take a look at it?

**Comment by deathmarine** [comment]
Procyon errors are being closed.
